import { describe, it, expect, afterAll } from "vitest";
import fs from "fs";
import path from "path";
import type { Edge, Node } from "../../types";
import { RoadNetwork } from "../../modules/RoadNetwork";
import { sortedNodeIds } from "../../modules/pathfinding/landmarks";

/**
 * ALT on the REAL Nairobi road network (~323k nodes / ~656k edges).
 *
 * `data/network.geojson` is generated by `@moveet/network` and gitignored, so
 * this suite skips itself when the file is absent (CI, fresh clones). It is the
 * only place the landmark work is exercised at production scale, which is where
 * both the payoff and the risk live:
 *
 *  1. Routes must be IDENTICAL to the pre-ALT heuristic. `PATHFINDING_LANDMARKS=0`
 *     restores exactly the old haversine bound, so an L=0 run is a faithful
 *     baseline. Over long random cross-city pairs this doubles as the empirical
 *     admissibility check — an overestimating heuristic would surface as a
 *     different (costlier) path.
 *  2. Nodes expanded per route must drop substantially.
 *  3. Both must still hold with incidents active.
 */

const networkPath = path.join(__dirname, "..", "..", "..", "data", "network.geojson");
const hasRealNetwork = fs.existsSync(networkPath);

/** Long-running by design: two full graph builds plus ~66 cross-city A* searches. */
const TIMEOUT_MS = 600_000;
/** Random start/end pairs compared without incidents. */
const PAIRS = 25;
/** How many of those pairs are re-run with incidents applied. */
const INCIDENT_PAIRS = 8;

interface PairResult {
  key: string;
  route: string;
  expanded: number;
}

interface Collected {
  plain: PairResult[];
  withIncidents: PairResult[];
  incidentEdgeIds: string[];
  nodeCount: number;
  buildMs: number;
}

/** Deterministic PRNG so both runs sample the exact same node pairs. */
function mulberry32(seed: number): () => number {
  let a = seed;
  return () => {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function describeRoute(route: { edges: Edge[]; distance: number } | null): string {
  if (!route) return "NO_ROUTE";
  return `${route.distance.toFixed(12)}|${route.edges.map((e) => e.id).join(">")}`;
}

/**
 * Builds the real network at a given landmark count and runs the whole
 * comparison battery against it. The `RoadNetwork` stays local so the ~750 MB
 * graph is collectable before the next build.
 */
function collect(landmarkCount: string): Collected {
  const previous = process.env.PATHFINDING_LANDMARKS;
  process.env.PATHFINDING_LANDMARKS = landmarkCount;
  try {
    const started = Date.now();
    const network = new RoadNetwork(networkPath);
    const buildMs = Date.now() - started;

    // @ts-expect-error — private graph, as the other RoadNetwork tests do.
    const nodes = network.nodes as Map<string, Node>;
    // Sorted ids make the sample identical across builds.
    const ids = sortedNodeIds(nodes.keys());
    const random = mulberry32(20260725);

    const pairs: Array<[string, string]> = [];
    while (pairs.length < PAIRS) {
      const a = ids[Math.floor(random() * ids.length)];
      const b = ids[Math.floor(random() * ids.length)];
      if (a !== b) pairs.push([a, b]);
    }

    const run = (): PairResult[] =>
      pairs.map(([startId, endId]) => {
        const route = network.findRoute(nodes.get(startId)!, nodes.get(endId)!);
        return {
          key: `${startId}->${endId}`,
          route: describeRoute(route),
          expanded: network.lastExpandedNodes,
        };
      });

    const plain = run();

    // Incident set derived from the first route's own edges, so it actually
    // perturbs the search rather than penalising untravelled roads. Because the
    // routes are asserted identical, both runs derive the identical set — which
    // the test verifies rather than assumes.
    const firstRoute = network.findRoute(nodes.get(pairs[0][0])!, nodes.get(pairs[0][1])!);
    const routeEdgeIds = firstRoute ? firstRoute.edges.map((e) => e.id) : [];
    const incidents = new Map<string, number>();
    routeEdgeIds.forEach((id, i) => {
      // Mix slowdowns with hard closures so both dynamic-cost branches are hit.
      if (i % 7 === 0) incidents.set(id, 0);
      else if (i % 3 === 0) incidents.set(id, 0.2);
    });
    network.setIncidentEdges(new Map(incidents));

    const withIncidents = pairs.slice(0, INCIDENT_PAIRS).map(([startId, endId]) => {
      const route = network.findRoute(nodes.get(startId)!, nodes.get(endId)!);
      return {
        key: `${startId}->${endId}`,
        route: describeRoute(route),
        expanded: network.lastExpandedNodes,
      };
    });

    return {
      plain,
      withIncidents,
      incidentEdgeIds: [...incidents.keys()].sort(),
      nodeCount: nodes.size,
      buildMs,
    };
  } finally {
    if (previous === undefined) delete process.env.PATHFINDING_LANDMARKS;
    else process.env.PATHFINDING_LANDMARKS = previous;
  }
}

const totals = (results: PairResult[]): number => results.reduce((sum, r) => sum + r.expanded, 0);

describe.skipIf(!hasRealNetwork)("ALT landmarks on the real road network", () => {
  let baseline: Collected;
  let withAlt: Collected;

  // Populated by the first test and reported at the end — these are the numbers
  // the optimisation is justified by, so they are printed rather than hidden.
  const report: string[] = [];
  afterAll(() => {
    if (report.length > 0) console.log(`\n${report.join("\n")}\n`);
  });

  it(
    "produces byte-identical routes to the pre-ALT haversine heuristic",
    () => {
      baseline = collect("0");
      withAlt = collect("4");

      expect(withAlt.nodeCount).toBe(baseline.nodeCount);
      expect(withAlt.plain.length).toBe(PAIRS);
      // Guard against a degenerate sample of unreachable pairs making this vacuous.
      expect(baseline.plain.filter((r) => r.route !== "NO_ROUTE").length).toBeGreaterThan(
        PAIRS / 2
      );

      for (let i = 0; i < PAIRS; i++) {
        expect(withAlt.plain[i].key).toBe(baseline.plain[i].key);
        expect(`${withAlt.plain[i].key}: ${withAlt.plain[i].route}`).toBe(
          `${baseline.plain[i].key}: ${baseline.plain[i].route}`
        );
      }

      const basePops = totals(baseline.plain);
      const altPops = totals(withAlt.plain);
      report.push(
        `[ALT] graph: ${baseline.nodeCount.toLocaleString()} nodes`,
        `[ALT] build: ${baseline.buildMs}ms (L=0) -> ${withAlt.buildMs}ms (L=4), ` +
          `preprocessing ~${withAlt.buildMs - baseline.buildMs}ms`,
        `[ALT] expanded/route: ${Math.round(basePops / PAIRS).toLocaleString()} (haversine) -> ` +
          `${Math.round(altPops / PAIRS).toLocaleString()} (ALT), ` +
          `${(basePops / altPops).toFixed(2)}x fewer`
      );
    },
    TIMEOUT_MS
  );

  it("expands dramatically fewer nodes per route", () => {
    const basePops = totals(baseline.plain);
    const altPops = totals(withAlt.plain);
    expect(altPops).toBeGreaterThan(0);
    // Measured ~4.1x on the Nairobi extract with 4 landmarks; assert a
    // conservative 2x so ordinary data churn cannot flake the build.
    expect(basePops / altPops).toBeGreaterThan(2);
    // Every individual route should shrink too, not just the aggregate.
    for (let i = 0; i < PAIRS; i++) {
      expect(withAlt.plain[i].expanded).toBeLessThanOrEqual(baseline.plain[i].expanded);
    }
  });

  it("keeps routes identical while incidents are active", () => {
    // Both runs must have derived the same incident set, otherwise the
    // comparison below would be meaningless.
    expect(withAlt.incidentEdgeIds).toEqual(baseline.incidentEdgeIds);
    expect(baseline.incidentEdgeIds.length).toBeGreaterThan(0);

    expect(withAlt.withIncidents.length).toBe(INCIDENT_PAIRS);
    for (let i = 0; i < INCIDENT_PAIRS; i++) {
      expect(`${withAlt.withIncidents[i].key}: ${withAlt.withIncidents[i].route}`).toBe(
        `${baseline.withIncidents[i].key}: ${baseline.withIncidents[i].route}`
      );
    }

    // Incidents only ever raise cost, so the landmark bound stays admissible and
    // the search still shrinks.
    const basePops = totals(baseline.withIncidents);
    const altPops = totals(withAlt.withIncidents);
    expect(basePops / altPops).toBeGreaterThan(2);
  });
});
