services:
  simulator:
    build: .
    volumes:
      - ./data/network.geojson:/app/data/network.geojson:ro
    environment:
      - UPDATE_INTERVAL=300
      - USE_ADAPTER=true
      - ADAPTER_URL=http://adapter:5011
    ports:
      - "5010:3000"
  adapter:
    build: ../adapter
    environment:
      - SOURCE_TYPE=static
      - SINK_TYPES=console
    ports:
      - "5011:5011"
  ui:
    build: ../ui
    ports:
      - "5012:8080"
